// Auto-generated by build_resources.py on 2026-05-29 11:52
// Sources: NCERT (ncert.nic.in) + CBSE Academic (cbseacademic.nic.in)
// DO NOT edit manually — re-run  python ncert_crawler/build_resources.py  to refresh

// --- Types ---

export type ResourceType = 'solutions' | 'syllabus' | 'sample-paper' | 'notes' | 'books'
export type ClassGroup   = 'early' | 'primary' | 'middle' | 'high'

export interface ResourceLink {
  type:  ResourceType
  label: string
  href:  string
}

export interface SubjectResource {
  subject: string
  icon:    string
  links:   ResourceLink[]
}

export interface ClassResource {
  classLabel: string
  classGroup: ClassGroup
  subjects:   SubjectResource[]
}

// --- Class Groups ---

export const classGroups: { id: ClassGroup; label: string; classes: string[] }[] = [
  { id: 'early',   label: 'Early Years',   classes: ['Nursery', 'KG', 'Pre-Primary'] },
  { id: 'primary', label: 'Primary',       classes: ['Class 1','Class 2','Class 3','Class 4','Class 5'] },
  { id: 'middle',  label: 'Middle School', classes: ['Class 6','Class 7','Class 8'] },
  { id: 'high',    label: 'High School',   classes: ['Class 9','Class 10','Class 11','Class 12'] },
]

// --- Resources by Class ---

export const classResources: ClassResource[] = [
  {
    classLabel: "Class 1",
    classGroup: 'primary',
    subjects: [
      {
        subject: "EVS",
        icon:    'Leaf',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?aess1=0-8" },
        ],
      },
      {
        subject: "English",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?aeen1=0-8" },
        ],
      },
      {
        subject: "Hindi",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?aehl1=0-23" },
        ],
      },
      {
        subject: "Mathematics",
        icon:    'Calculator',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?aemh1=0-14" },
        ],
      },
    ],
  },
  {
    classLabel: "Classes 1-5",
    classGroup: 'primary',
    subjects: [
      {
        subject: "All",
        icon:    'BookOpen',
        links: [
          { type: 'syllabus', label: "CBSE Syllabus", href: "https://cbseacademic.nic.in/web_material/CurriculumMain25/Primary/Class1-5.pdf" },
        ],
      },
    ],
  },
  {
    classLabel: "Class 2",
    classGroup: 'primary',
    subjects: [
      {
        subject: "EVS",
        icon:    'Leaf',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?bess1=0-12" },
        ],
      },
      {
        subject: "English",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?been1=0-10" },
        ],
      },
      {
        subject: "Hindi",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?behl1=0-25" },
        ],
      },
      {
        subject: "Mathematics",
        icon:    'Calculator',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?bemh1=0-15" },
        ],
      },
    ],
  },
  {
    classLabel: "Class 3",
    classGroup: 'primary',
    subjects: [
      {
        subject: "EVS",
        icon:    'Leaf',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?cess1=0-24" },
        ],
      },
      {
        subject: "English",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?ceen1=0-10" },
        ],
      },
      {
        subject: "Hindi",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?cehl1=0-25" },
        ],
      },
      {
        subject: "Mathematics",
        icon:    'Calculator',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?cemh1=0-14" },
        ],
      },
    ],
  },
  {
    classLabel: "Class 4",
    classGroup: 'primary',
    subjects: [
      {
        subject: "EVS",
        icon:    'Leaf',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?dess1=0-27" },
        ],
      },
      {
        subject: "English",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?deen1=0-10" },
        ],
      },
      {
        subject: "Hindi",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?dehl1=0-28" },
        ],
      },
      {
        subject: "Mathematics",
        icon:    'Calculator',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?demh1=0-14" },
        ],
      },
    ],
  },
  {
    classLabel: "Class 5",
    classGroup: 'primary',
    subjects: [
      {
        subject: "EVS",
        icon:    'Leaf',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?eess1=0-22" },
        ],
      },
      {
        subject: "English",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?eeen1=0-10" },
        ],
      },
      {
        subject: "Hindi",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?eehl1=0-18" },
        ],
      },
      {
        subject: "Mathematics",
        icon:    'Calculator',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?eemh1=0-14" },
        ],
      },
    ],
  },
  {
    classLabel: "Class 6",
    classGroup: 'middle',
    subjects: [
      {
        subject: "English",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?feen1=0-10" },
        ],
      },
      {
        subject: "Hindi",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?fehl1=0-18" },
        ],
      },
      {
        subject: "Mathematics",
        icon:    'Calculator',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?femh1=0-14" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?feep1=0-14" },
        ],
      },
      {
        subject: "Sanskrit",
        icon:    'BookMarked',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?fesl1=0-15" },
        ],
      },
      {
        subject: "Science",
        icon:    'FlaskConical',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?fesc1=0-16" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?feep2=0-16" },
        ],
      },
      {
        subject: "Social Science",
        icon:    'Globe',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?fess1=0-9" },
        ],
      },
    ],
  },
  {
    classLabel: "Classes 6-8",
    classGroup: 'middle',
    subjects: [
      {
        subject: "All",
        icon:    'BookOpen',
        links: [
          { type: 'syllabus', label: "CBSE Syllabus", href: "https://cbseacademic.nic.in/web_material/CurriculumMain25/UpperPrimary/Class6-8.pdf" },
        ],
      },
    ],
  },
  {
    classLabel: "Class 7",
    classGroup: 'middle',
    subjects: [
      {
        subject: "English",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?geen1=0-10" },
        ],
      },
      {
        subject: "Hindi",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?gehl1=0-20" },
        ],
      },
      {
        subject: "Mathematics",
        icon:    'Calculator',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?gemh1=0-15" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?geep1=0-15" },
        ],
      },
      {
        subject: "Sanskrit",
        icon:    'BookMarked',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?gesl1=0-15" },
        ],
      },
      {
        subject: "Science",
        icon:    'FlaskConical',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?gesc1=0-18" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?geep2=0-18" },
        ],
      },
      {
        subject: "Social Science",
        icon:    'Globe',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?gess1=0-9" },
        ],
      },
    ],
  },
  {
    classLabel: "Class 8",
    classGroup: 'middle',
    subjects: [
      {
        subject: "English",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?heen1=0-10" },
        ],
      },
      {
        subject: "Hindi",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?hehl1=0-18" },
        ],
      },
      {
        subject: "Mathematics",
        icon:    'Calculator',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?hemh1=0-16" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?heep1=0-16" },
        ],
      },
      {
        subject: "Sanskrit",
        icon:    'BookMarked',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?hesl1=0-15" },
        ],
      },
      {
        subject: "Science",
        icon:    'FlaskConical',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?hesc1=0-18" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?heep2=0-18" },
        ],
      },
      {
        subject: "Social Science",
        icon:    'Globe',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?hess1=0-10" },
        ],
      },
    ],
  },
  {
    classLabel: "Class 9",
    classGroup: 'high',
    subjects: [
      {
        subject: "Economics",
        icon:    'BarChart2',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?iess3=0-4" },
        ],
      },
      {
        subject: "English",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?ieen1=0-11" },
        ],
      },
      {
        subject: "Hindi",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?iehl1=0-17" },
        ],
      },
      {
        subject: "Mathematics",
        icon:    'Calculator',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?iemh1=0-15" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?ieep1=0-15" },
        ],
      },
      {
        subject: "Science",
        icon:    'FlaskConical',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?iesc1=0-15" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?ieep2=0-15" },
        ],
      },
      {
        subject: "Social Science",
        icon:    'Globe',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?iess1=0-5" },
        ],
      },
    ],
  },
  {
    classLabel: "Classes 9-10",
    classGroup: 'high',
    subjects: [
      {
        subject: "All",
        icon:    'BookOpen',
        links: [
          { type: 'syllabus', label: "CBSE Syllabus", href: "https://cbseacademic.nic.in/web_material/CurriculumMain25/Secondary/Class9-10.pdf" },
        ],
      },
    ],
  },
  {
    classLabel: "Class 10",
    classGroup: 'high',
    subjects: [
      {
        subject: "Accountancy",
        icon:    'Receipt',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassX_2024_25/ElementsBookKeepingAccountancy-SQP.pdf" },
        ],
      },
      {
        subject: "Business Studies",
        icon:    'Briefcase',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassX_2024_25/ElementsBusiness-SQP.pdf" },
        ],
      },
      {
        subject: "Computer Science",
        icon:    'Monitor',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassX_2024_25/ComputerApplication-SQP.pdf" },
        ],
      },
      {
        subject: "Economics",
        icon:    'BarChart2',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?jess3=0-5" },
        ],
      },
      {
        subject: "English",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?jeen1=0-11" },
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassX_2024_25/EnglishL-SQP.pdf" },
        ],
      },
      {
        subject: "General / Marking Scheme",
        icon:    'FileText',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassX_2024_25/NCC-SQP.pdf" },
        ],
      },
      {
        subject: "Hindi",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?jehl1=0-17" },
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassX_2024_25/HindiCourseA-SQP.pdf" },
        ],
      },
      {
        subject: "Mathematics",
        icon:    'Calculator',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?jemh1=0-15" },
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassX_2024_25/MathsBasic-SQP.pdf" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?jeep1=0-15" },
        ],
      },
      {
        subject: "Sanskrit",
        icon:    'BookMarked',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassX_2024_25/Sanskrit-SQP.pdf" },
        ],
      },
      {
        subject: "Science",
        icon:    'FlaskConical',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?jesc1=0-16" },
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassX_2024_25/Science-SQP.pdf" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?jeep2=0-16" },
        ],
      },
      {
        subject: "Social Science",
        icon:    'Globe',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?jess1=0-5" },
        ],
      },
    ],
  },
  {
    classLabel: "Class 11",
    classGroup: 'high',
    subjects: [
      {
        subject: "Accountancy P1",
        icon:    'Receipt',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?keac1=0-9" },
        ],
      },
      {
        subject: "Biology",
        icon:    'Leaf',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?kebo1=0-22" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?keep4=0-22" },
        ],
      },
      {
        subject: "Business Studies",
        icon:    'Briefcase',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?kebs1=0-6" },
        ],
      },
      {
        subject: "Chemistry",
        icon:    'TestTube',
        links: [
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?keep3=0-14" },
        ],
      },
      {
        subject: "Chemistry P1",
        icon:    'TestTube',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?kech1=0-14" },
        ],
      },
      {
        subject: "Chemistry P2",
        icon:    'TestTube',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?kech2=0-7" },
        ],
      },
      {
        subject: "Economics",
        icon:    'BarChart2',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?keec1=0-6" },
        ],
      },
      {
        subject: "English",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?keen1=0-11" },
        ],
      },
      {
        subject: "History",
        icon:    'Clock',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?kehe1=0-4" },
        ],
      },
      {
        subject: "Mathematics",
        icon:    'Calculator',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?kemh1=0-16" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?keep1=0-16" },
        ],
      },
      {
        subject: "Physics",
        icon:    'Zap',
        links: [
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?keep2=0-15" },
        ],
      },
      {
        subject: "Physics P1",
        icon:    'Zap',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?keph1=0-15" },
        ],
      },
      {
        subject: "Physics P2",
        icon:    'Zap',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?keph2=0-6" },
        ],
      },
      {
        subject: "Political Science",
        icon:    'Scale',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?keps1=0-10" },
        ],
      },
    ],
  },
  {
    classLabel: "Classes 11-12",
    classGroup: 'high',
    subjects: [
      {
        subject: "All",
        icon:    'BookOpen',
        links: [
          { type: 'syllabus', label: "CBSE Syllabus", href: "https://cbseacademic.nic.in/web_material/CurriculumMain25/SrSecondary/Class11-12.pdf" },
        ],
      },
    ],
  },
  {
    classLabel: "Class 12",
    classGroup: 'high',
    subjects: [
      {
        subject: "Accountancy",
        icon:    'Receipt',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2024_25/Accountancy-SQP.pdf" },
        ],
      },
      {
        subject: "Accountancy P1",
        icon:    'Receipt',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?leac1=0-9" },
        ],
      },
      {
        subject: "Accountancy P2",
        icon:    'Receipt',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?leac2=0-4" },
        ],
      },
      {
        subject: "Biology",
        icon:    'Leaf',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?lebo1=0-16" },
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2024_25/Biology-SQP.pdf" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?leep4=0-16" },
        ],
      },
      {
        subject: "Business Studies",
        icon:    'Briefcase',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?lebs1=0-5" },
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2024_25/BusinessStudies-SQP.pdf" },
        ],
      },
      {
        subject: "Chemistry",
        icon:    'TestTube',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2024_25/Chemistry-SQP.pdf" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?leep3=0-9" },
        ],
      },
      {
        subject: "Chemistry P1",
        icon:    'TestTube',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?lech1=0-9" },
        ],
      },
      {
        subject: "Chemistry P2",
        icon:    'TestTube',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?lech2=0-7" },
        ],
      },
      {
        subject: "Computer Science",
        icon:    'Monitor',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2024_25/InformaticsPractices-SQP.pdf" },
        ],
      },
      {
        subject: "Economics",
        icon:    'BarChart2',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?leec1=0-6" },
        ],
      },
      {
        subject: "English",
        icon:    'BookOpen',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?leen1=0-12" },
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2024_25/EnglishCore-SQP.pdf" },
        ],
      },
      {
        subject: "General / Marking Scheme",
        icon:    'FileText',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2024_25/Arabic-SQP.pdf" },
        ],
      },
      {
        subject: "Hindi",
        icon:    'BookOpen',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2024_25/HindiElective-SQP.pdf" },
        ],
      },
      {
        subject: "History",
        icon:    'Clock',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?lehe1=0-4" },
        ],
      },
      {
        subject: "Mathematics",
        icon:    'Calculator',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2024_25/Applied-Maths-SQP.pdf" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?leep1=0-13" },
        ],
      },
      {
        subject: "Mathematics P1",
        icon:    'Calculator',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?lemh1=0-13" },
        ],
      },
      {
        subject: "Mathematics P2",
        icon:    'Calculator',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?lemh2=0-6" },
        ],
      },
      {
        subject: "Physics",
        icon:    'Zap',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2024_25/Physics-SQP.pdf" },
          { type: 'solutions', label: "Exemplar Problems & Solutions", href: "https://ncert.nic.in/textbook.php?leep2=0-8" },
        ],
      },
      {
        subject: "Physics P1",
        icon:    'Zap',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?leph1=0-8" },
        ],
      },
      {
        subject: "Physics P2",
        icon:    'Zap',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?leph2=0-6" },
        ],
      },
      {
        subject: "Political Science",
        icon:    'Scale',
        links: [
          { type: 'books', label: "NCERT Books", href: "https://ncert.nic.in/textbook.php?leps1=0-9" },
        ],
      },
      {
        subject: "Sanskrit",
        icon:    'BookMarked',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2024_25/SanskritCore-SQP.pdf" },
        ],
      },
      {
        subject: "Science",
        icon:    'FlaskConical',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2024_25/ComputerScience-SQP.pdf" },
        ],
      },
      {
        subject: "Social Science",
        icon:    'Globe',
        links: [
          { type: 'sample-paper', label: "Sample Papers", href: "https://cbseacademic.nic.in/web_material/SQP/ClassXII_2024_25/Economics-SQP.pdf" },
        ],
      },
    ],
  },
]

// --- Useful Quick Links ---

export const usefulLinks = [
  { label: 'NCERT Official',    href: 'https://ncert.nic.in/',                           icon: 'BookMarked'    },
  { label: 'CBSE Official',     href: 'https://cbseacademic.nic.in/',                    icon: 'GraduationCap' },
  { label: 'myAIS School App',  href: 'https://edusecure.org/aisbanur/login/login.aspx', icon: 'Smartphone'    },
  { label: 'CBSE Results',      href: 'https://results.cbse.nic.in/',                    icon: 'Trophy'        },
]

// --- Resource Type Styles ---

export const resourceTypeStyles: Record<ResourceType, { bg: string; text: string; label: string }> = {
  'solutions':    { bg: 'bg-primary/10',          text: 'text-primary',       label: 'Exemplar Solutions'  },
  'syllabus':     { bg: 'bg-[#2D7D46]/10',        text: 'text-[#2D7D46]',     label: 'Syllabus'            },
  'sample-paper': { bg: 'bg-primary-light/10',    text: 'text-primary-light', label: 'Sample Papers'       },
  'notes':        { bg: 'bg-[#6B6259]/10',        text: 'text-[#6B6259]',     label: 'Worksheets'          },
  'books':        { bg: 'bg-[#1A1A1A]/10',        text: 'text-[#1A1A1A]',     label: 'NCERT Books'         },
}
